### ISSUE TITLE
Wiki link gives 503

### ISSUE THREAD

**Issue by nikhita** [archwomen/website#5]
https://archwomen.org/wiki/ gives a `503 - Service Not Available`.

As a consequence, all links pointing to the wiki give a 503 as well. (Example - the link here: https://github.com/archwomen/meetings#meetings)

**Comment by meskarune** [comment]
Thanks so much for your report. I believe everything is working now as expected, sorry I didn't update this issue sooner >< I sometimes forget about the github since its a mirror.
